### ISSUE TITLE
その他

### ISSUE THREAD

**Issue by hirainra** [NoriakiHirai/infoExchange#13]
[bitbucketConnection.zip](https://github.com/NoriakiHirai/infoExchange/files/1663510/bitbucketConnection.zip)

**Comment by NoriakiHirai** [comment]
[Blockchain勉強会_Blockchainとは.zip](https://github.com/NoriakiHirai/infoExchange/files/1679326/Blockchain._Blockchain.zip)

**Comment by NoriakiHirai** [comment]
[Blockchain勉強会-1回目.zip](https://github.com/NoriakiHirai/infoExchange/files/1679334/Blockchain.-1.zip)

**Comment by NoriakiHirai** [comment]
sudo apt-get install \ 
    apt-transport-https \ 
    ca-certificates \ 
    curl \ 
    software-properties-common

**Comment by NoriakiHirai** [comment]
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

**Comment by NoriakiHirai** [comment]
sudo add-apt-repository \ 
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \ 
   $(lsb_release -cs) \ 
   stable"

**Comment by NoriakiHirai** [comment]
FROM nginx 
RUN echo '<h1>Hello, Docker!</h1>' > /usr/share/nginx/html/index.html

**Comment by NoriakiHirai** [comment]
sudo docker build -t mynginx:v1 .

**Comment by NoriakiHirai** [comment]
[Desktop.zip](https://github.com/NoriakiHirai/infoExchange/files/1683632/Desktop.zip)

**Comment by NoriakiHirai** [comment]
名前 | サイズ | 説明
-- | -- | --
uint | 256-bit | unsigned   integer。ビットワイズとunsignedな算術計算が可能
int | 256-bit | signed   integer。ビットワイズとunsignedな算術計算が可能
real | 256-bit | signed fixed-point   quantity, 127-bit left of the point, 128-bit right
string32 | 256-bit | 最大の長さ   32bytes(256-bit)のzero-terminatedなASCII文字列
address |   | アカウントID。160-bitハッシュ型と似ている
bool |   | boolean

**Comment by NoriakiHirai** [comment]
[201802.zip](https://github.com/NoriakiHirai/infoExchange/files/1709390/201802.zip)

**Comment by NoriakiHirai** [comment]
## 勉強会打合せ議事録

日時：2/9


【今回の課題について】
・授業でテキストをやらなかったので、
未実施であった第15回のリストをコーディングする。


【次回までのタスク】
・アンケート準備 ⇒ 平井
・各設計書の雛形とサンプル ⇒ 平井


【終わりの挨拶について】
塩田さんの総括のみ


【懇親会について】
3月9日の勉強会後に懇親会実施。
日時：3月9日（金） 18:30~21:00
場所：未定（ニュートーキョー以外）
参加者：検討中（塩田さん）
備考：PCは会社で預かる。


【その他】
Java勉強会の打合せは、本日(2/9)で終了。

次回の打合せは、来年度の勉強会に関して検討を行う予定。
日時は2月部会（2/22）の後。

**Comment by NoriakiHirai** [comment]
[第8・9回勉強会構成.zip](https://github.com/NoriakiHirai/infoExchange/files/1710255/8.9.zip)

**Comment by NoriakiHirai** [comment]
###### Web勤怠
https://kintai.shinwart.co.jp/wtsm/login/?0

###### ActiveMail
https://am.shinwart.co.jp/am_bin/amlogin

**Comment by NoriakiHirai** [comment]
◆起動
・guestユーザー
テーブルの作成などはできない
mysql -u guest -p
pass:ユーザ名と同じ

・rootユーザー
テーブルの作成などができる
mysql -u root -p
pass:ユーザ名と同じ

◆操作
show databases;

create database equipment;

#使用するテーブルの決定
use equipment;

create table equipment (
id int not null auto_increment primary key,
name varchar(255),
strength int,
agility int,
hp int
)
;

show tables;

#テーブルの構造を確認する
desc equipment;

#列の追加
alter table equipment add category char(2) after name;

#列の削除
alter table equipment drop column category;

#データの挿入
insert into equipment
(name, category, strength, agility, hp) values
('剣', '01', 3, 0, 1);

insert into equipment
(name, category, strength, agility, hp) values
('魔法の杖', '01', 4, 1, 1),
('短剣', '01', 1, 1, 1),
('甲冑', '02', 0, 0, 5),
('鎖帷子', '02', 0, 0, 3),
('盾', '02', 0, 0, 4);

**Comment by NoriakiHirai** [comment]
[第8・9回勉強会構成.zip](https://github.com/NoriakiHirai/infoExchange/files/1716630/8.9.zip)

**Comment by hirainra** [comment]
[DesignTemplete9.zip](https://github.com/NoriakiHirai/infoExchange/files/1718876/DesignTemplete9.zip)

**Comment by hirainra** [comment]
[8.9.zip](https://github.com/NoriakiHirai/infoExchange/files/1718882/8.9.zip)

**Comment by NoriakiHirai** [comment]
###### 壁紙
https://www.mugendai-web.jp/wallpaper2018

**Comment by NoriakiHirai** [comment]
[201802.zip](https://github.com/NoriakiHirai/infoExchange/files/1740053/201802.zip)

**Comment by hirainra** [comment]
[3550_平井識章_20180228_交通費_01.zip](https://github.com/NoriakiHirai/infoExchange/files/1769715/3550_._20180228_._01.zip)

**Comment by hirainra** [comment]
<p>参加が決定しました。</p>

<p>登録の確認が完了しました。お客様のバーチャル シートを確保しております。ご自身の予定表にウェビナーへの参加日時を書き留めてください。以下のリンクより、カレンダーにウェビナーへの参加を簡単に追加できます。また、参加日時に使用するリンクもあります。</p>

【ウェブ セミナー】解説 Azure DevOps Project ～Visual Studio Team Services / Team Foundation Server で自動化をしたい方にお勧めです～
 2018年3月13日（火）
 12:00-13:00 - <a href=
'http://emails.microsoft.com/f00QEbq0Q80cVQ0KGWE2Y04'
><span style="text-decoration:none;">日付を保存する</span></a>
 
ウェビナーに参加するには、ここをクリックしてください <[[https://event.on24.com/interface/registration/autoreg/index.html?eventid=1564928&sessionid=1&key=72F98B77B2A0DC392924CE07C9B9F495&firstname=%E5%B9%B3%E4%BA%95&lastname=%E8%AD%98%E7%AB%A0&company=%E9%88%B4%E4%B8%8E%E3%82%B7%E3%83%B3%E3%83%AF%E3%83%BC%E3%83%88%E6%A0%AA%E5%BC%8F%E4%BC%9A%E7%A4%BE&email=nhirai@shinwart.co.jp&job_title=&country=&zip=&work_phone=]]>
マイクロソフトの本メッセージは、お客様がご購入またはご利用になったプログラム、サービス、および製品に関する重要な内容を記載しております。マイクロソフトはお客様のプライバシーを尊重しております。当社のプライバシーに関する声明をお読みください。< http://go.microsoft.com/fwlink/?LinkId=248681>

**Comment by hirainra** [comment]
<p>参加が決定しました。</p>

<p>登録の確認が完了しました。お客様のバーチャル シートを確保しております。ご自身の予定表にウェビナーへの参加日時を書き留めてください。以下のリンクより、カレンダーにウェビナーへの参加を簡単に追加できます。また、参加日時に使用するリンクもあります。</p>

【ウェブ セミナー】本格化するサーバーレス コンピューティングと Azure Functions の進化
 2018年3月14日（水）
16:30-17:30 - <a href=
'http://emails.microsoft.com/P0c0WcEGqQ0Y940V0QhE3K0'
><span style="text-decoration:none;">日付を保存する </span></a>
 
ウェビナーに参加するには、ここをクリックしてください <[[https://event.on24.com/interface/registration/autoreg/index.html?eventid=1565747&sessionid=1&key=4A4667ADB0DDC294C5531F2EE0919FE1&firstname=%E5%B9%B3%E4%BA%95&lastname=%E8%AD%98%E7%AB%A0&company=%E9%88%B4%E4%B8%8E%E3%82%B7%E3%83%B3%E3%83%AF%E3%83%BC%E3%83%88%E6%A0%AA%E5%BC%8F%E4%BC%9A%E7%A4%BE&email=nhirai@shinwart.co.jp&job_title=Developer+%2F+Engineer&country=&zip=&work_phone=]]>
マイクロソフトの本メッセージは、お客様がご購入またはご利用になったプログラム、サービス、および製品に関する重要な内容を記載しております。マイクロソフトはお客様のプライバシーを尊重しております。当社のプライバシーに関する声明をお読みください。< http://go.microsoft.com/fwlink/?LinkId=248681>

**Comment by NoriakiHirai** [comment]
テキストエディタ
http://brackets.io/

**Comment by hirainra** [comment]
AWS クラウドサービス活用資料集 
ブラックベルトなどの資料はこちらに格納されている
https://aws.amazon.com/jp/aws-jp-introduction/

**Comment by hirainra** [comment]
[Azure研修資料.zip](https://github.com/NoriakiHirai/infoExchange/files/1823366/Azure.zip)

**Comment by hirainra** [comment]
業務遂行度の特記事項
・ブロックチェーン基盤調査では、チームリーダーとして各メンバーの進捗管理や調査内容の品質管理を、適切に実施できた。
・貿易プラットフォーム開発では、
・お薬手帳アプリの暗号化においては、

**Comment by hirainra** [comment]
[一般職考課表（情報）_3550_平井識章.zip](https://github.com/NoriakiHirai/infoExchange/files/1897452/_3550_.zip)

**Comment by hirainra** [comment]
https://www.linkedin.com/e/v2?e=aqjhyp-jg7zqlyw-k8&t=lun&midToken=AQFE_-RVAcOoKQ&ek=email_welcome_abi_v2&li=18&m=unsub&ts=unsub&loid=AQH98Ov9e88TLQAAAWLjPtmtvMch90Dps-zVz7OF6116z0VSz8OrcfvgqeVAOKklyZo0RWJPvcEevr-5iq38ZTJdr6L1H1EVrr9xf-y5FJY&eid=aqjhyp-jg7zqlyw-k8

**Comment by hirainra** [comment]
https://connect.awswebcasts.com/blackbelt-data-lake-architecture-on-aws-20180424/event/login.html?campaign-id=em_cs_invite&login=noriasrock%40gmail.com

**Comment by hirainra** [comment]
### 大阪北部地震 被害報告書
[被害状況連絡表_3550_平井識章.zip](https://github.com/NoriakiHirai/infoExchange/files/2113776/_3550_.zip)
